### ISSUE TITLE
what can it vue

### ISSUE THREAD

**Issue by jswhisperer** [NovusTheory/vue-nodegui-example#4]
which vue features work? v-model? lifecycles?

**Comment by NovusTheory** [comment]
For later questions that involve vue-nodegui itself (as this is just an example project) please use https://github.com/NovusTheory/vue-nodegui

In short it currently cannot do v-model but it does and can do lifecycles. It does or should support v-on, but only for button click and the event listener isn't correctly removed yet. vue-nodegui is still a very big WIP

**Comment by jswhisperer** [comment]
Thanks for the response and I admire your ambition with this project!
